[package]
name = "reflectub"
version = "0.0.1"
edition = "2018"

[dependencies]
reqwest = { version = "0.11.3", features = ["blocking", "json"] }
serde = { version = "1.0.126", features = ["derive"] }
